//
// connection.hpp
// ~~~~~~~~~~~~~~
//
// Copyright (c) 2003-2012 Christopher M. Kohlhoff (chris at kohlhoff dot com)
// Copyright (c) 2013 Alex Caudill (alex at furosys.com)
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#pragma once

#include <boost/asio.hpp>
#include <boost/array.hpp>
#include <boost/noncopyable.hpp>
#include <boost/shared_ptr.hpp>
#include <boost/enable_shared_from_this.hpp>
#include "http/reply.hpp"
#include "http/request.hpp"
#include "http/request_handler.hpp"
#include "http/request_parser.hpp"

namespace market {
    namespace http {
        /// Represents a single connection from a client.
        class connection : public boost::enable_shared_from_this<connection>, private boost::noncopyable {
            public:
                /// Construct a connection with the given io_service.
                explicit connection(boost::asio::io_service& io_service, request_handler& handler);
                /// Get the socket associated with the connection.
                boost::asio::ip::tcp::socket& socket();
                /// Start the first asynchronous operation for the connection.
                void start();
            private:
                /// Handle completion of a read operation.
                void handle_read(const boost::system::error_code& e, std::size_t bytes_transferred);
                /// Handle completion of a write operation.
                void handle_write(const boost::system::error_code& e);
                /// Socket for the connection.
                boost::asio::ip::tcp::socket socket_;
                /// The handler used to process the incoming request.
                request_handler& request_handler_;
                /// Buffer for incoming data.
                boost::array<char, 8192> buffer_;
                /// The incoming request.
                request request_;
                /// The parser for the incoming request.
                request_parser request_parser_;
                /// The reply to be sent back to the client.
                reply reply_;
        };
        typedef boost::shared_ptr<connection> connection_ptr;
    } // namespace market
} // namespace http
