//
// request_parser.hpp
// ~~~~~~~~~~~~~~~~~~
//
// Copyright (c) 2003-2012 Christopher M. Kohlhoff (chris at kohlhoff dot com)
// Copyright (c) 2013 Alex Caudill (alex at furosys.com)
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#pragma once

#include <boost/logic/tribool.hpp>
#include <boost/tuple/tuple.hpp>

namespace market {
    namespace http {
        struct request;
        /// Parser for incoming requests.
        class request_parser {
            public:
                /// Construct ready to parse the request method.
                request_parser();
                /// Reset to initial parser state.
                void reset();
                /// Parse some data. The tribool return value is true when a complete request
                /// has been parsed, false if the data is invalid, indeterminate when more
                /// data is required. The InputIterator return value indicates how much of the
                /// input has been consumed.
                template <typename InputIterator>
                boost::tuple<boost::tribool, InputIterator> parse(request& req, InputIterator begin, InputIterator end) {
                    while (begin != end) {
                        boost::tribool result = consume(req, *begin++);
                        if (result || !result) { 
                            return boost::make_tuple(result, begin);
                        }
                    }
                    boost::tribool result = boost::indeterminate;
                    return boost::make_tuple(result, begin);
                }
            private:
                /// Handle the next character of input.
                boost::tribool consume(request& req, char input);
                /// Check if a byte is an HTTP character.
                static bool is_char(int c);
                /// Check if a byte is an HTTP control character.
                static bool is_ctl(int c);
                /// Check if a byte is defined as an HTTP tspecial character.
                static bool is_tspecial(int c);
                /// Check if a byte is a digit.
                static bool is_digit(int c);
                /// The current state of the parser.
                enum state {
                    method_start,
                    method,
                    uri,
                    http_version_h,
                    http_version_t_1,
                    http_version_t_2,
                    http_version_p,
                    http_version_slash,
                    http_version_major_start,
                    http_version_major,
                    http_version_minor_start,
                    http_version_minor,
                    expecting_newline_1,
                    header_line_start,
                    header_lws,
                    header_name,
                    space_before_header_value,
                    header_value,
                    expecting_newline_2,
                    expecting_newline_3
                } state_;
        };
    } // namespace market
} // namespace http
