//
// connection.cpp
// ~~~~~~~~~~~~~~
//
// Copyright (c) 2003-2012 Christopher M. Kohlhoff (chris at kohlhoff dot com)
// Copyright (c) 2013 Alex Caudill (alex at furosys.com)
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#include "http/connection.hpp"
#include <vector>
#include <boost/bind.hpp>
#include "http/request_handler.hpp"

namespace http {
    namespace market {

        connection::connection(boost::asio::io_service& io_service, request_handler& handler) : socket_(io_service), request_handler_(handler) {}

        boost::asio::ip::tcp::socket& connection::socket() {
            return socket_;
        }

        void connection::start() {
            socket_.async_read_some(
                boost::asio::buffer(buffer_),
                boost::bind(
                    &connection::handle_read, 
                    shared_from_this(), 
                    boost::asio::placeholders::error, 
                    boost::asio::placeholders::bytes_transferred
                )
            );
        }

        void connection::handle_read(const boost::system::error_code& e, std::size_t bytes_transferred) {
            if (!e) {
                boost::tribool result;
                boost::tie(result, boost::tuples::ignore) = request_parser_.parse(request_, buffer_.data(), buffer_.data() + bytes_transferred);

                if (result) {
                    request_handler_.handle_request(request_, reply_);
                    boost::asio::async_write(
                        socket_, 
                        reply_.to_buffers(), 
                        boost::bind(
                            &connection::handle_write, 
                            shared_from_this(), 
                            boost::asio::placeholders::error
                        )
                    );
                } else if (!result) {
                    reply_ = reply::stock_reply(reply::bad_request);
                    boost::asio::async_write(
                        socket_, 
                        reply_.to_buffers(),
                        boost::bind(
                            &connection::handle_write,
                            shared_from_this(),
                            boost::asio::placeholders::error
                        )
                    );
                } else {
                    socket_.async_read_some(
                        boost::asio::buffer(buffer_),
                        boost::bind(
                            &connection::handle_read,
                            shared_from_this(),
                            boost::asio::placeholders::error,
                            boost::asio::placeholders::bytes_transferred
                        )
                    );
                }
            }
            // If an error occurs then no new asynchronous operations are started. This
            // means that all shared_ptr references to the connection object will
            // disappear and the object will be destroyed automatically after this
            // handler returns. The connection class's destructor closes the socket.
        }

        void connection::handle_write(const boost::system::error_code& e) {
            if (!e) {
            // Initiate graceful connection closure.
                boost::system::error_code ignored_ec;
                socket_.shutdown(boost::asio::ip::tcp::socket::shutdown_both, ignored_ec);
            }
            // No new asynchronous operations are started. This means that all shared_ptr
            // references to the connection object will disappear and the object will be
            // destroyed automatically after this handler returns. The connection class's
            // destructor closes the socket.
        }
    } // namespace market
} // namespace http
